w3c/deviceorientation

spec-source-orientation.html

some minor changes (the first two as suggested by Giri):
- updated the last modification date of the specification
- added "(until July 2012)" for the previous editors. I took the last commit by andreip@ as reference month for this.
- replaced "absolutedeviceorientation" -> "deviceorientationabsolute"

bring the spec up to date

---

spec-source-orientation.html

Inspired by https://w3c.github.io/selection-api/
Fixes https://github.com/w3c/deviceorientation/issues/20

Add a Participate section with links to GitHub

---

spec-source-orientation.html

to clarify 'null' event case for device motion as after https://github.com/w3c/deviceorientation/pull/40

Update spec-source-orientation.html - clarify null case for motion

---

spec-source-orientation.html

updated references with the latest W3C spec drafts for the upcoming publication

updated references with the latest W3C spec drafts

---

spec-source-orientation.html

For more information, please refer to https://github.com/heycam/webidl/issues/365
Fixes: #45

Use [Exposed=Window] extended attribute

---

index.html

Make security and privacy normative

---

index.bs
index.html

* Add Previous Version
* Make the group collectively be the new editor
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/72.html" title="Last updated on Apr 3, 2019, 5:13 AM UTC (f67de19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/72/fd6286e...f67de19.html" title="Last updated on Apr 3, 2019, 5:13 AM UTC (f67de19)">Diff</a>

Update spec metadata

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/95.html" title="Last updated on Jun 6, 2021, 5:14 AM UTC (a7ae7d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/95/87f5077...a7ae7d7.html" title="Last updated on Jun 6, 2021, 5:14 AM UTC (a7ae7d7)">Diff</a>

http -> https

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/rakuco/deviceorientation/pull/103.html" title="Last updated on Jun 10, 2022, 2:12 PM UTC (1528346)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/103/21c8ea9...rakuco:1528346.html" title="Last updated on Jun 10, 2022, 2:12 PM UTC (1528346)">Diff</a>

s/user agent/user agents/ in compassneedscalibration description.

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/111.html" title="Last updated on Apr 21, 2023, 8:36 AM UTC (cac6abe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/111/e03086d...cac6abe.html" title="Last updated on Apr 21, 2023, 8:36 AM UTC (cac6abe)">Diff</a>

Add new editors

---

index.bs

The language used to describe the previous Security & Privacy is not
very precise, but using the right terms would make the sentence long
and harder to understand.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 2, 2024, 10:47 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fdeviceorientation%2F56ea2f99ca4bc78e033292a338c4c95ac0099759%2Findex.bs&force=1&md-warning=not%20ready)
```
<!DOCTYPE …
```

changes: Mention #136 in the Permissions Policy integration item

---

index.bs

Context: https://github.com/w3cping/privacy-request/issues/128#issuecomment-1985286838
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/144.html" title="Last updated on Mar 8, 2024, 6:49 PM UTC (b33c584)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/144/ccffbb5...b33c584.html" title="Last updated on Mar 8, 2024, 6:49 PM UTC (b33c584)">Diff</a>

Add an inline issue for the maximum sampling frequency cap

---

index.bs

This text is authored by APA WG and its APA consensus is recorded in: https://lists.w3.org/Archives/Public/public-apa-admin/2024Mar/0000.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/150.html" title="Last updated on Mar 19, 2024, 9:28 AM UTC (b3a01b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/150/1d42f14...b3a01b6.html" title="Last updated on Mar 19, 2024, 9:28 AM UTC (b3a01b6)">Diff</a>

Add Accessibility considerations

---

index.bs

Would like to join the Editorial team, as I'd like to make sure things align with WebKit.
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/deviceorientation/pull/146.html" title="Last updated on Mar 12, 2024, 3:10 AM UTC (81e63a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/146/6e2d033...marcoscaceres:81e63a5.html" title="Last updated on Mar 12, 2024, 3:10 AM UTC (81e63a5)">Diff</a>

chore: add Marcos to editorial team

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/166.html" title="Last updated on May 2, 2024, 8:30 AM UTC (3ce87b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/166/37c29da...3ce87b4.html" title="Last updated on May 2, 2024, 8:30 AM UTC (3ce87b4)">Diff</a>

Chore: enable markdown shorthands in index.bs

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/167.html" title="Last updated on May 2, 2024, 8:34 AM UTC (b34aeae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/167/41a27ec...b34aeae.html" title="Last updated on May 2, 2024, 8:34 AM UTC (b34aeae)">Diff</a>

Editorial: use bikeshed shorthands for task source section

---

index.bs

Small wording tweaks to the introduction
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/156.html" title="Last updated on May 3, 2024, 5:02 AM UTC (410c243)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/156/56179cb...410c243.html" title="Last updated on May 3, 2024, 5:02 AM UTC (410c243)">Diff</a>

Editorial: reword the Introduction section

---

index.bs

Reword the scope section to better reflect the spec's intent.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/158.html" title="Last updated on May 2, 2024, 1:38 AM UTC (cf46818)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/158/37c29da...cf46818.html" title="Last updated on May 2, 2024, 1:38 AM UTC (cf46818)">Diff</a>

Editorial: rework scope

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/169.html" title="Last updated on May 3, 2024, 5:19 AM UTC (98d7634)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/169/876932f...98d7634.html" title="Last updated on May 3, 2024, 5:19 AM UTC (98d7634)">Diff</a>

Editorial: rewrite abstract

---

index.bs

More small bikeshed fixes and simplifications.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/174.html" title="Last updated on May 8, 2024, 1:28 AM UTC (38b6766)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/174/55db7e5...38b6766.html" title="Last updated on May 8, 2024, 1:28 AM UTC (38b6766)">Diff</a>

Editorial: more bikeshed shorthand usage

---

index.bs

Made the algorithm a bit simpler.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/173.html" title="Last updated on May 8, 2024, 4:05 AM UTC (71877c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/173/abbeb98...71877c2.html" title="Last updated on May 8, 2024, 4:05 AM UTC (71877c2)">Diff</a>

Editorial: simplify "significant change in orientation" algorithm

---

index.bs

Improved use of infra usage too.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/177.html" title="Last updated on May 9, 2024, 3:03 PM UTC (f424d35)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/177/a8bb8fb...f424d35.html" title="Last updated on May 9, 2024, 3:03 PM UTC (f424d35)">Diff</a>

Editorial: simplify parse orientation data reading algo

---

index.bs

I am leaving Intel soon and do not yet know if/when I will be able to dedicate time to this spec.
***
<a href="https://pr-preview.s3.amazonaws.com/rakuco/deviceorientation/pull/188.html" title="Last updated on Oct 24, 2024, 8:37 AM UTC (0db6320)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/188/d80265a...rakuco:0db6320.html" title="Last updated on Oct 24, 2024, 8:37 AM UTC (0db6320)">Diff</a>

Retire as editor

---

.github/workflows/auto-publish.yml

switch echidna from WD to CRD

---

index.bs

Closed #190.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/191.html" title="Last updated on Feb 11, 2025, 11:29 PM UTC (ea4207c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/191/65a71aa...ea4207c.html" title="Last updated on Feb 11, 2025, 11:29 PM UTC (ea4207c)">Diff</a>

Process: Set CRS comment deadline to 2025-03-15
