spec-source-orientation.html
Fixes https://github.com/w3c/deviceorientation/issues/9
This also removes trailing whitespace.
=> Remove the [Callback] extended attribute

spec-source-orientation.html
This is required:
http://heycam.github.io/webidl/#prod-Dictionary
http://heycam.github.io/webidl/#prod-Interface
=> Add missing semicolons to IDL blocks

spec-source-orientation.html
This changes only the bare minimum necessary, there are many links in
the document that could be HTTPS but are not.
=> Use HTTPS as needed to avoid mixed content warnings

spec-source-orientation.html
to address issue https://github.com/w3c/deviceorientation/issues/24
=> add security and privacy section

spec-source-orientation.html
This change makes the IDL for the DeviceMotionEvent.interval consistent with the normative description of this attribute, which requires it to be initialized to 0 if not specified. This implies that this attribute should not be nullable and simply have a default value of 0.
Resolves #39.
=> Make interval IDL consistent with normative text.

index.html
Update some spec metadata for now. IMHO we should move the spec to Bikeshed/ReSpec before publishing a new WD, since that would make publication easier.
There are 29 errors (and 5 warnings) in the Pubrules checker now: https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fdeviceorientation%2F&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004
=> Update spec metadata

index.html
There is no section 5.2, and use cases are listed in 6.1. Update the
reference accordingly after commits 8380389 and 1323549 (both titled "Update
spec-source-orientation.html").
=> Reference the "use cases" section by the right number

index.html
It is invalid for a dictionary member that resolves to a nullable type
to be marked with '?'. This change is effectively a no-op because these
fields remain nullable.
Resolves #54.
=> Remove '?' from dictionary members of DeviceMotionEventInit

index.html
This is already in Blink's IDL:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/device_orientation/WindowDeviceOrientation.idl
=> Add the ondeviceorientationabsolute event handler attribute

index.bs, index.html
Besides style changes, the following changes were made:
- use standard Status of this document for an Editor's Draft
- add missing IDL block to the compassneedscalibration Event section
- update [HTML51] references to [HTML]
- editorial: use Bikeshed standard Feedback header
- editorial: link all occurrences of definitions
- editorial: rename all "Section X" links to "Section title" links
- editorial: split references to normative and informative subsections
- editorial: add IDL index
Fix #53
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/62.html" title="Last updated on Jan 30, 2019, 2:53 PM UTC (a92514f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/62/02426f1...a92514f.html" title="Last updated on Jan 30, 2019, 2:53 PM UTC …
=> Convert spec source into Bikeshed format

index.bs, index.html
Rename exposed interfaces, and *Init dictionaries.
Fix #58
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/63.html" title="Last updated on Jan 31, 2019, 10:26 AM UTC (b363303)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/63/29569e9...b363303.html" title="Last updated on Jan 31, 2019, 10:26 AM UTC (b363303)">Diff</a>
=> Remove [NoInterfaceObject]

index.bs
As the next step towards fully removing `DeviceOrientationEvent` and `DeviceMotionEvent` in non-secure browsing contexts (which is tracked by #47), this change marks all interfaces with the `[SecureContext]` extended attribute, but leaves the `ondeviceorientation` or `ondevicemotion` attributes on `window` available in non-secure contexts for now.
Based on analysis from [HTTPArchive](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/5yqfAXibz1I), it is expected that when user agents implement this change, the risk of breaking existing web applications is virtually negligible.
***
<a href="https://pr-preview.s3.amazonaws.com/engedy/deviceorientation/pull/65.html" title="Last updated on Feb 27, 2019, 9:26 AM UTC (978b40a)">Preview</a> | <a …
=> Restrict all interfaces to secure contexts

index.bs, index.html
Add requestPermission() static operation to both DeviceOrientationEvent and DeviceMotionEvent
so that JavaScript can request permission to use the API so that user agents may ask the user
before sharing the device orientation & motion with the page.
Fixes: #57
***
<a href="https://pr-preview.s3.amazonaws.com/cdumez/deviceorientation/pull/68.html" title="Last updated on Mar 15, 2019, 11:18 PM UTC (deeac36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/68/26a13b4...cdumez:deeac36.html" title="Last updated on Mar 15, 2019, 11:18 PM UTC (deeac36)">Diff</a>
=> Add permission request API

index.bs
The Device Orientation spec uses a right-handed system with Y being positive
upwards, while the CSS coordinate system uses a left-handed system with Y
being positive downwards. Additionally, DOMMatrixReadOnly.rotate() and its
DOMMatrix.rotateSelf() counterpart both apply rotations in a Z-Y'-X'' order
that differs from the Z-X'-Y'' order here and can also lead to confusion and
wrong rotations.
Chromium's own DevTools code for overriding Device Orientation values has
had multiple issues with this over the years, the latest one being
https://crbug.com/1137281, so it is probably a good idea to make it more
explicit to others.
***
<a href="https://pr-preview.s3.amazonaws.com/rakuco/deviceorientation/pull/92.html" title="Last updated on Dec 2, 2020, 2:19 PM UTC (d85373b)">Preview</a> | <a …
=> Add a note explaining how the coordinate system differs from the CSS one.

index.bs
Add a missing `]` in that was preventing Bikeshed from creating a proper
reference link in the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/rakuco/deviceorientation/pull/93.html" title="Last updated on Jun 1, 2021, 10:29 AM UTC (f2bbd3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/93/8221924...rakuco:f2bbd3c.html" title="Last updated on Jun 1, 2021, 10:29 AM UTC (f2bbd3c)">Diff</a>
=> Fix reference to HTML spec in devicemotion event description.

index.bs
When  the phone is upright, gravity adds 9.8 to the y-axis, so `accelerationIncludingGravity` is `{ x: v^2/r, y: 9.8, z: 0 }` (not 9.8 on z-axis as currently)
closes #98
***
<a href="https://pr-preview.s3.amazonaws.com/chaals/deviceorientation/pull/99.html" title="Last updated on Jul 8, 2021, 3:55 PM UTC (1f9fffa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/99/e5ee004...chaals:1f9fffa.html" title="Last updated on Jul 8, 2021, 3:55 PM UTC (1f9fffa)">Diff</a>
=> Fix example 9

index.bs
see dom.spec.whatwg.org/#firing-events-example
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/deviceorientation/pull/102.html" title="Last updated on Jun 8, 2022, 3:25 PM UTC (a94bfe8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/102/9d26c4a...dontcallmedom:a94bfe8.html" title="Last updated on Jun 8, 2022, 3:25 PM UTC (a94bfe8)">Diff</a>
=> Align with DOM phrasing on firing events

index.bs
- Indentation
- JS != JSON
***
<a href="https://pr-preview.s3.amazonaws.com/tomayac/deviceorientation/pull/104.html" title="Last updated on Sep 15, 2022, 6:33 PM UTC (869d8c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/104/faca6fe...tomayac:869d8c9.html" title="Last updated on Sep 15, 2022, 6:33 PM UTC (869d8c9)">Diff</a>
=> Improve syntax highlighting

index.bs
This concept is now referred to as "transient activation".
Fixed #105.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/106.html" title="Last updated on Jan 9, 2023, 7:08 PM UTC (3dd77f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/106/5791e0b...3dd77f0.html" title="Last updated on Jan 9, 2023, 7:08 PM UTC (3dd77f0)">Diff</a>
=> Update reference to "triggered by user activation"

index.bs
Fixes https://github.com/w3c/deviceorientation/issues/82.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/deviceorientation/pull/88.html" title="Last updated on Feb 23, 2021, 2:53 AM UTC (1e5d7a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/88/b95751e...foolip:1e5d7a1.html" title="Last updated on Feb 23, 2021, 2:53 AM UTC (1e5d7a1)">Diff</a>
=> Drop duplicate PermissionState definition

index.bs
There are no implementations of this event.
Fixed #38.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/107.html" title="Last updated on Mar 7, 2023, 12:57 AM UTC (7f1c214)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/107/7e1e1d9...7f1c214.html" title="Last updated on Mar 7, 2023, 12:57 AM UTC (7f1c214)">Diff</a>
=> Remove the oncompassneedscalibration event

index.bs
Couple of informative sections are not explicitly marked as non-normative.
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/deviceorientation/pull/108.html" title="Last updated on Apr 1, 2023, 2:56 AM UTC (2f45469)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/108/07d52cd...marcoscaceres:2f45469.html" title="Last updated on Apr 1, 2023, 2:56 AM UTC (2f45469)">Diff</a>
=> Editorial: mark sections as non-normative

index.bs
The change in #106 only fixed one instance of "triggered by user interaction". This fixes the other.
Fixed #109.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/110.html" title="Last updated on Apr 12, 2023, 6:16 PM UTC (e4067d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/110/23db732...e4067d0.html" title="Last updated on Apr 12, 2023, 6:16 PM UTC (e4067d0)">Diff</a>
=> Update remaining reference to "triggered by user activation"

index.bs
Use more modern spec terminology in the list of requirements for firing
device orientation and motion events:
- Use navigables and concepts defined for navigables when dealing with
windows and documents.
- Stop referring to the PAGE-VISIBILITY spec, as it was merged into HTML a
few years ago. Use a document's visibility state instead.
- Use more precise terms when laying out the same-origin requirements
between the top-level traversable and its child navigables. The new
paragraph is a mouthful, but also more precise.
- Instead of referring to the SECURE-CONTEXTS spec, use HTML's definition of
"secure context".
This change should not cause any behavioral or user-detectable changes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/114.html" title="Last updated on …
=> editorial: Reword requirements in "Security and privacy considerations"

index.bs
- Use the more common structure that just says "The `ONFOO` attribute is an
event handler IDL attribute for the `ONFOO` event handler, whose event
handeler event type is `FOO`.
- Use `<a event>foo</a>` instead of `{{foo}}` to reference an event type.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/115.html" title="Last updated on Nov 7, 2023, 10:06 AM UTC (c17ff1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/115/5e62e4e...c17ff1b.html" title="Last updated on Nov 7, 2023, 10:06 AM UTC (c17ff1b)">Diff</a>
=> editorial: Use more precise event handling terms, modernize others

index.bs
The latter is part of the Compat spec and is mostly targeted at mobile
devices and supporting existing web content, whereas the Screen Orientation
spec contains a more modern and maintained API for tracking and controlling
changes to screen orientation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/116.html" title="Last updated on Nov 7, 2023, 10:13 AM UTC (63f18cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/116/5e62e4e...63f18cc.html" title="Last updated on Nov 7, 2023, 10:13 AM UTC (63f18cc)">Diff</a>
=> editorial: Refer to [[SCREEN-ORIENTATION]] instead of the orientationchange event

index.bs
The 3 changes here are related but I feel like they should be separate commits.
The idea is to 1) make the spec easier to read by not mixing explanations about the motion and orientation models with descriptions of IDL attributes 2) make the explanations easier to understand by clarifying some concepts, especially the Device Orientation-related ones.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/117.html" title="Last updated on Nov 9, 2023, 12:46 PM UTC (7db68d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/117/fc30f5e...7db68d7.html" title="Last updated on Nov 9, 2023, 12:46 PM UTC (7db68d7)">Diff</a>
=> editorial: Add a separate section describing model, rewrite contents

index.bs
This is a PR with multiple commits for clarity, but the really important one is the last one, whose commit message I'll reproduce here. Having this structure in place makes it a lot easier to add permissions policy integration or make the Permissions API integration required, for example.
---
The idea is to make this section less hand-wavy and easier to change in the
future by defining algorithms and steps more clearly while not making any
user-visible changes.
Readability:
- Rename the "Description" section to "API"
- Start each "API" subsection with an IDL block rather than prose.
- Move the `<dfn>`s for attributes and methods to their normative
descriptions rather than the IDL blocks.
- Use the wording currently recommended by the Web IDL spec to define
attributes and methods.
- Add …
=> editorial: Define API section more normatively and with more <dfn>s

index.bs
This section summarizes substantial changes and notable editorial improvements to guide review.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/125.html" title="Last updated on Dec 11, 2023, 12:49 PM UTC (91ab4b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/125/e81d70f...91ab4b5.html" title="Last updated on Dec 11, 2023, 12:49 PM UTC (91ab4b5)">Diff</a>
=> Add Changes section

security-privacy-self-assessment.md
This is a prerequisite for Privacy and Security reviews: https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review
@rakuco @reillyeon given you're on top of this specification I'm expecting you to help fill in this questionnaire. I pre-populated this doc with some content to help get the work started. I don't claim those responses to be complete or even accurate so I seek your expert review. Thank you for your contributions.
#125 is complementary material to help guide reviewers. I acknowledge that this specification last time reached its CR maturity in 2016 and at that time this self-assessment was not required, and we don't have a prior record. However, we have completed these reviews and done self-assessment for the Generic Sensor family of specs in 2018 which can be reused …
=> Add Security and Privacy Self-Review Questionnaire

index.bs
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 30, 2024, 12:44 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fdeviceorientation%2F206ded8a8c0b9a1d3b07d116180e69272f4983d2%2Findex.bs&force=1&md-warning=not%20ready)
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an …
=> editorial: Fix grammar and missing words in Permissions Policy note

security-privacy-self-assessment.md
Follow-up to #126.
Rewrite the answer to question 2.13, "How does this specification
distinguish between behavior in first-party and third-party contexts?" by
mentioning that the integration with the Permissions Policy specification
does cause this spec to distinguish between first-party and third-party
context.
=> Security & Privacy Questionnaire: Mention Permissions Policy integration

index.bs
This addresses a conflict that was introduced in #121:
- The presence of the Permissions Policy integration means usage of the
Device Orientation API can be allowed in third-party iframes provided that
the right tokens are in place.
- The "Security and privacy considerations" section contains a requirement
that events are fired only on child navigables that are same-origin with
the top-level traversable.
The latter was introduced in #25 and served as a stop-gap measure before
Permissions Policy integration was added.
The current implementation status is:
- Blink never implemented the same-origin requirement, but added Permissions
Policy integration in 2018.
- WebKit has always implemented Permissions Policy integration.
- Gecko implements the same-origin requirement (see Mozilla bug …
=> Replace same-origin Security & Privacy requirement with Permissions Policy one

index.bs
The requirement to only fire events on documents whose visibility state is
"visible" was already in the normative Security and Privacy section, but it
was not integrated into the algorithms that fire said events.
Related to #33.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/140.html" title="Last updated on Feb 13, 2024, 1:28 PM UTC (f989d04)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/140/36b567e...f989d04.html" title="Last updated on Feb 13, 2024, 1:28 PM UTC (f989d04)">Diff</a>
=> Check visibility state in algorithms that fire events

index.bs
We were only requiring alpha, beta, and gamma to be null. It makes sense to
also require implementations to set absolute to the same value as well.
At the time of writing, this is done for completeness' sake though:
- Blink implements this behavior and sets absolute to false when a
deviceorientation cannot be provided, and to true for
deviceorientationabsolute events.
- Gecko does not send any events if it cannot provide readings (e.g. when
there are no sensors available).
- WebKit only ships an iOS implementation, whose IDL does not even have an
absolute attribute.
Fixes #119.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/139.html" title="Last updated on Feb 14, 2024, 8:01 AM UTC (1607c06)">Preview</a> | <a …
=> DeviceOrientationEvent: Define absolute's value on error

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/149.html" title="Last updated on Mar 13, 2024, 5:51 PM UTC (7e1cef8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/149/1d42f14...7e1cef8.html" title="Last updated on Mar 13, 2024, 5:51 PM UTC (7e1cef8)">Diff</a>
=> editorial: Identify at risk features and their causes

index.bs
Should be 'self' not "self"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/164.html" title="Last updated on May 2, 2024, 5:54 AM UTC (3f0dfb3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/164/37c29da...3f0dfb3.html" title="Last updated on May 2, 2024, 5:54 AM UTC (3f0dfb3)">Diff</a>
=> Editorial: fix allowlist 'self' cross reference

index.bs
Highlighting was a bit wonky... plus a bit more modern now.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/157.html" title="Last updated on May 2, 2024, 1:40 AM UTC (db47510)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/157/37c29da...db47510.html" title="Last updated on May 2, 2024, 1:40 AM UTC (db47510)">Diff</a>
=> Editorial: fixup/modernize examples

index.bs
@reillyeon, I don't think we should include "Event"... in the title. The spec provides a Model for device orientation and motion, which then are expressed in the API as events. But like with other specs, (e.g., [Fetch](https://fetch.spec.whatwg.org), [Permissions](https://www.w3.org/TR/permissions/), [Screen orientation](https://www.w3.org/TR/screen-orientation), etc.) we generally wouldn't put how it's represented as the API in the title.
To be sure, if one Googles, Bings, or even searches on DuckDuckGo, for "device orientation and motion spec" the spec is already found - so this wouldn't affect how findable this spec is.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/168.html" title="Last updated on May 3, 2024, 7:55 AM UTC (d3639dc)">Preview</a> | <a …
=> Editorial: change spec title

index.bs
Already covered in the introduction and the various examples.
Plus some of the use cases are not great: like try to detect a gesture is not an appropriate use of the API.
Depends on https://github.com/w3c/deviceorientation/pull/158
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/159.html" title="Last updated on May 4, 2024, 2:13 AM UTC (cdb03ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/159/831284e...cdb03ac.html" title="Last updated on May 4, 2024, 2:13 AM UTC (cdb03ac)">Diff</a>
=> Editorial: drop Use cases and Requirements section

index.bs
Drop redundant text and just let bikeshed generate the conformance section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/155.html" title="Last updated on May 7, 2024, 4:10 AM UTC (e0e4ee7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/155/80974dd...e0e4ee7.html" title="Last updated on May 7, 2024, 4:10 AM UTC (e0e4ee7)">Diff</a>
=> Editorial: automatically generate the conformance section

index.bs
These definitions were kinda dangling. Nicer to have them linked up.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/160.html" title="Last updated on May 2, 2024, 1:56 AM UTC (e0c701c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/160/37c29da...e0c701c.html" title="Last updated on May 2, 2024, 1:56 AM UTC (e0c701c)">Diff</a>
=> Editorial: contextualize x, y, z in model a bit more

index.bs
Normative references to wikipedia is probably not ideal - specially for a general knowledge topic.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/163.html" title="Last updated on May 7, 2024, 5:00 AM UTC (dba5559)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/163/21d1db5...dba5559.html" title="Last updated on May 7, 2024, 5:00 AM UTC (dba5559)">Diff</a>
=> Editorial: small fixup to Device Motion section

index.bs
The permission sections was confusing features and permissions.
APIs can be classified into powerful features, but only the permissions matter.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/165.html" title="Last updated on May 7, 2024, 4:59 AM UTC (7d8d3bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/165/876932f...7d8d3bf.html" title="Last updated on May 7, 2024, 4:59 AM UTC (7d8d3bf)">Diff</a>
=> Editorial: rewrite permissions section

index.bs
Improve use of Infra and bikeshed shorthands.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/170.html" title="Last updated on May 7, 2024, 5:05 AM UTC (fb2660a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/170/21d1db5...fb2660a.html" title="Last updated on May 7, 2024, 5:05 AM UTC (fb2660a)">Diff</a>
=> Editorial: cleanup requestPermission() algorithm

index.bs
This doesn't change any of the algorithm. Just bikeshed usage.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/171.html" title="Last updated on May 7, 2024, 5:11 AM UTC (8577e5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/171/21d1db5...8577e5b.html" title="Last updated on May 7, 2024, 5:11 AM UTC (8577e5b)">Diff</a>
=> Editorial: cleanup fire an orientation event algorithm

index.bs
Couple more little fixes. No actual text changes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/172.html" title="Last updated on May 8, 2024, 4:04 AM UTC (2e84838)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/172/abbeb98...2e84838.html" title="Last updated on May 8, 2024, 4:04 AM UTC (2e84838)">Diff</a>
=> Editorial: use more bikeshed shorthands

CONTRIBUTING.md
Line break was breaking link to license
=> chore: fix link in CONTRIBUTING.md

index.bs
Use more bikeshed goodies... doesn't change the algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/175.html" title="Last updated on May 8, 2024, 1:30 AM UTC (dd2cd38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/175/55db7e5...dd2cd38.html" title="Last updated on May 8, 2024, 1:30 AM UTC (dd2cd38)">Diff</a>
=> Editorial: use bikeshed shorthands in requestPermission() algorithm

index.bs
Just bikeshed stuff... doesn't change the algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/pull/176.html" title="Last updated on May 21, 2024, 12:43 AM UTC (29c2bb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/deviceorientation/176/39c015e...29c2bb2.html" title="Last updated on May 21, 2024, 12:43 AM UTC (29c2bb2)">Diff</a>
=> Editorial: use bikeshed shorthands for devicemotion firing steps
